# Generated by Django 3.0.6 on 2020-07-05 14:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note_type', models.CharField(choices=[('book', 'Book'), ('doc', 'Documentary'), ('thinker', 'Thinker/Person'), ('misc', 'Other/Miscellaneous'), (None, 'Select type...')], max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('notes', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('completed', 'completed')], default='to do', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(to='feed.Categories')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
