# Generated by Django 3.0.5 on 2020-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('completed', 'completed')], default='to do', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
