# Generated by Django 3.0.5 on 2020-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200420_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_type',
            field=models.CharField(choices=[('book', 'book'), ('doc', 'documentary'), ('thinker', 'thinker/person')], max_length=100),
        ),
    ]
