# Generated by Django 3.0.5 on 2020-04-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200421_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_type',
            new_name='medium',
        ),
    ]
