# Generated by Django 3.0.6 on 2020-06-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200616_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
    ]
