# Generated by Django 3.0.6 on 2020-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200616_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
