# Generated by Django 3.0.6 on 2020-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_categories_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='feed.Categories'),
        ),
    ]
