# Generated by Django 3.0.5 on 2020-04-24 16:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200424_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
