# Generated by Django 3.0.5 on 2020-04-25 13:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200424_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='post',
            name='medium',
            field=models.CharField(choices=[('book', 'Book'), ('doc', 'Documentary'), ('thinker', 'Thinker/Person'), ('misc', 'Miscellaneous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
