# Generated by Django 3.0.5 on 2020-04-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20200425_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='medium',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='note_type',
            field=models.CharField(choices=[('book', 'Book'), ('doc', 'Documentary'), ('thinker', 'Thinker/Person'), ('misc', 'Other/Miscellaneous')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
